version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=Faten123.
      - MYSQL_DATABASE=schoolmanagementsystem
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: on-failure
    env_file: ./.env
    ports:
      - 4200:4200
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/schoolmanagementsystem?useSSL=false",
        "spring.datasource.username" : "faten",
        "spring.datasource.password" : "Faten123.",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: